apiVersion: v1
kind: Service
metadata:
  labels:
    run: cstar-db # we label run: ... all the resources that run a particular service (here cstar-db)
  name: cstar-db-srv # name will be the -... three letters abbreviation of the Kind
  namespace: default
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: cstar-db # this will select from the template.spec.metadata.labels (the pod)
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: cstar-db
  name: cstar-db-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-db
  template:
    metadata:
      labels:
        run: cstar-db
    spec:
      containers:
      - image: localhost:5000/cstar-db:{{imageTag}}
        imagePullPolicy: Always
        name: cstar-db-ctn
        ports:
        - containerPort: 5432
          protocol: TCP
      restartPolicy: Always

