apiVersion: v1
kind: Service
metadata:
  labels:
    run: cstar-queue
  name: cstar-queue-srv
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: cstar-queue # this will select from the template.spec.metadata.labels (the pod)
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cstar-queue-dep
  labels:
    run: cstar-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-queue
  template:
    metadata:
      labels:
        run: cstar-queue
    spec:
      containers:
      - image: localhost:5000/cstar-queue:{{imageTag}}
        imagePullPolicy: Always
        name: cstar-queue-ctn
        ports:
        - containerPort: 6379
          protocol: TCP
      restartPolicy: Always